import Head from 'next/head'
import Hero from '../components/Hero'
import Portfolio from '../components/Portfolio'
import Testimonial from '../components/Testimonial'


export default function Home() {
  return (
    <div>
      <Head>
        <title>MI_Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="https://thumbs.dreamstime.com/b/blue-letter-b-logo-power-blue-letter-b-logo-power-logo-luxury-minimalist-badge-logo-edge-contrast-color-logo-114749609.jpg" type="image/x-icon" />
      </Head>

      {/* Hero section */}
      <Hero/>
      {/* Portfolio */}
      <Portfolio/>
      {/* Testimonials */}
      <Testimonial/>

    
    </div>
  )
}
